### ISSUE TITLE
Can't add buddybuild

### ISSUE THREAD

**Issue by sahilNaranSzn1106** [marcells/node-build-monitor#50] opened 2017-06-09 20:02 UTC
I keep getting this error when trying to add a buddybuild to the config file
```
BuddyBuild.js:140
node-build-monitor 0.9.16 is listening on port 3000
/Users/san/Desktop/build-monitor/build-monitor/app/services/BuddyBuild.js:140
            var asyncBuildsQuery = body.map(function (app) {
                                        ^

TypeError: body.map is not a function
    at /Users/san/Desktop/build-monitor/build-monitor/app/services/BuddyBuild.js:140:41
    at Request._callback (/Users/san/Desktop/build-monitor/build-monitor/app/services/BuddyBuild.js:42:21)
    at Request.self.callback (/Users/san/Desktop/build-monitor/build-monitor/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/san/Desktop/build-monitor/build-monitor/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/san/Desktop/build-monitor/build-monitor/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)

Process finished with exit code 1
```
The service in the config file:
```
    {
      "name": "BuddyBuild",
      "configuration": {
        "project_name": "IOS",
        "app_id": "",
        "url": "https://dashboard.buddybuild.com/apps/5939*rest is ommitted*",
        "access_token": "JnsQSLH6k0d*rest is ommitted*",
        "build_id": "",
        "branch": "develop"
      }
    }
```

**Comment by marcells** [comment] 2017-06-17 13:00
Hi @sahilNaranSzn1106, could @sanjusoftware help you to resolve the issue?

**Comment by sahilNaranSzn1106** [comment] 2017-06-19 04:48
@marcells nope!

**Comment by sanjusoftware** [comment] 2017-06-19 05:16
sorry @sahilNaranSzn1106 .. I'll have a look at this today .. was away for some time.

**Comment by sahilNaranSzn1106** [comment] 2017-06-19 05:29
@sanjusoftware thank you!

**Comment by sanjusoftware** [comment] 2017-06-19 05:36
@sahilNaranSzn1106 the problem is that you are providing the appid in the buddy build URL itself.. remove that and make it likr following:

````json
{
      "name": "BuddyBuild",
      "configuration": {
        "project_name": "IOS",
        "app_id": "5939*rest is ommitted*",
        "url": "https://dashboard.buddybuild.com/apps",
        "access_token": "JnsQSLH6k0d*rest is ommitted*",
        "build_id": "",
        "branch": "develop"
      }
    }
````

In case, you are trying to make it for nultiple buddybuild apps, then omit the app_id totally and have the following:

````json
{
      "name": "BuddyBuild",
      "configuration": {
        "project_name": "IOS",
        "url": "https://dashboard.buddybuild.com/apps",
        "access_token": "JnsQSLH6k0d*rest is ommitted*",
        "build_id": "",
        "branch": "develop"
      }
    }
````
Let me know if that works for you

**Comment by sanjusoftware** [comment] 2017-06-20 02:26
@sahilNaranSzn1106 did the solution work for .. if it did, can we close this issue?

**Comment by sahilNaranSzn1106** [comment] 2017-06-20 04:05
@sanjusoftware I am busy testing it out now.

**Comment by sahilNaranSzn1106** [comment] 2017-06-20 04:18
@sanjusoftware Now it says that it cant read property branch of undefined

**Comment by marcells** [comment] 2017-09-03 11:07
@sahilNaranSzn1106 Can this issue be closed now?

**Comment by sahilNaranSzn1106** [comment] 2017-09-04 03:49
yes

**Comment by sanjusoftware** [comment] 2017-09-04 05:24
Alright then... @marcells, I think you'll have to close it then... I don't have the rights

**Closed** 2017-09-04 05:46 UTC
