### ISSUE TITLE
Display branch name and/or commit sha

### ISSUE THREAD

**Issue by rafaelmagu** [marcells/node-build-monitor#26] opened 2016-10-17 01:32 UTC
For builds that have either branch or commit details, we should display those on the board, for easier distinguishing between builds.

**Comment by rafaelmagu** [comment] 2016-10-21 23:41
Configurable from where? The commits would change constantly.

**Comment by marcells** [comment] 2016-10-25 12:27
Ah, okay. For which build system do you need this information?

**Comment by rafaelmagu** [comment] 2016-10-25 19:27
Currently, we're using a mixture of Jenkins, Travis and Wercker.

**Comment by marcells** [comment] 2016-11-10 21:14
Sorry for the late response. Currently there's a lot of work for me in my day job.

The problem is, that the VCS, which trigger a build can be very different. Maybe in some of them a branch concept even doesn't exist. And I don't think that all or most of the build services support forwarding this information.

**Comment by ntamas** [comment] 2017-10-04 15:42
Let me add my two cents here. In my organization, it would also be desirable to show the branch name and/or the commit SHA on the build monitor. The way I plan to implement it in my fork is to add extra properties (`branch` and `commit`) to the build object that is returned from, e.g., `simplifyBuild()` in `GitLab.js`, extend the `BuildViewModel` with the appropriate Knockout observables and then make a custom theme that makes use of these observables. Note that this is a non-breaking change: none of the default themes would need to know about these properties, and none of the other services would be required to provide `branch` and `commit` properties for the build objects - they are completely optional. However, this could be a *de facto* standard way of communicating branch and commit info for build systems that *do* provide this information so the maintainers of other build services in `node-build-monitor` can update their code when time allows.

@marcells I'd like to hear your opinion on this as I plan to submit a pull request with these changes or the GitLab service - if you say it's a no-no, I won't waste your time with the pull request and just keep the changes in my own fork.

**Comment by marcells** [comment] 2017-10-04 18:10
@ntamas Thanks, I'm fine with the change. But the UI of the theme should look nice, even if there is no commit/branch info available. In a later change, I could maybe add the info to the default theme.

**Comment by marcells** [comment] 2017-10-04 18:11
Maybe issue #76 could be resolved with that change, too.

**Comment by ntamas** [comment] 2017-10-04 18:23
> But the UI of the theme should look nice, even if there is no commit/branch info available.

Agreed - that's why I'm not incorporating the commit/branch info into the default themes; I leave it up to you to decide how these should be shown.

> Maybe issue #76 could be resolved with that change, too.

I think the environment is not included in the [response](https://docs.gitlab.com/ce/api/pipelines.html#get-a-single-pipeline) provided by the GitLab API, and the names of the pipeline stages need another request (see [response example here](https://docs.gitlab.com/ce/api/jobs.html#list-pipeline-jobs). I might do them at a later stage (we have `build`, `test` and `lint` steps in pipelines and it would be nice to know whether the pipeline failed in the build, the test or the lint stage), but I cannot promise anything definite yet.

**Comment by marcells** [comment] 2017-10-05 06:03
Alright, thanks for that info.

**Closed** 2019-02-21 19:24 UTC
Labels: enhancement
