### ISSUE TITLE
Does this work with TFS Git Repos

### ISSUE THREAD

**Issue by modulexcite** [marcells/node-build-monitor#69] opened 2017-09-15 15:04 UTC
Hi,

I've an **on-premise TFS 2015 server** and was wondering if this works with the git repositories on TFS. Currently, I've the following configuration in my `config.json` but can't seem to get it to work. Any help on this is greatly appreciated and I apologize if this is already documented somewhere.

node-build-monitor version: v0.9.21
TFS : 2015 on-premise
Client OS: Windows 7 x64
```json
{
	"monitor": {
		"interval": 30000,
		"numberOfBuilds": 12,
		"latestBuildOnly": false,
		"sortOrder": "date",
		"debug": true
	},
	"services": [{
		"name": "Tfs2015",
		"configuration": {
			"url": "http://tfs-server:8080/tfs/DefaultCollection/_git/TeamProject",
			"authentication": "ntlm",
			"username": "DOMAIN\\USERNAME",
			"password": "PASSWORD"
		}
	},
	{
		"name": "Tfs2015",
		"configuration": {
			"url": "http://tfs-server:8080/tfs/DefaultCollection/TeamProject",
			"authentication": "ntlm",
			"username": "DOMAIN\\USERNAME",
			"password": "PASSWORD"
		}
	},
	{
		"name": "Tfs2015",
		"configuration": {
			"url": "http://tfs-server:8080/tfs/DefaultCollection/TeamProject",
			"authentication": "ntlm",
			"username": "DOMAIN\\USERNAME",
			"password": "PASSWORD"
		}
	}]
}
```

**Comment by marcells** [comment] 2017-09-20 16:07
It's working for Git Repos, cause we use it internally in our company. The build configuration is independent of the version control. The first configuration looks wrong. The last two should work. You could try to remove the `authentication` lines.

**Comment by marcells** [comment] 2017-10-30 19:45
@modulexcite Any news here? Otherwise I would close the issue.

**Comment by modulexcite** [comment] 2017-10-30 20:56
Sorry about that, I forgot to update I got it working. Please close it, thank you for your help.

**Comment by marcells** [comment] 2017-10-31 03:22
No problem. Nice to hear, that the issue is resolved for you.

**Closed** 2017-10-31 03:24 UTC
Labels: question
